[Configuration]
BasedOn=..\UDKGame\Config\DefaultGame.ini

; Persist AP activation when Unreal regenerates UDKGame.ini on another PC.
[Engine.GameInfo]
DefaultGame=DD1Archipelago.APGameInfo
DefaultServerGame=DD1Archipelago.APGameInfo
